# Домашнее задание «Библиотека numpy. Вычислительные задачи»


## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [10]:
import numpy as np
N = 15
a = np.arange((N-1), -1, -1)
a

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.



In [13]:
n = 10
matrix = np.flip(np.diag(np.arange(0, n+1), k=0))
sample = []
i = 0
for sum_diag in matrix:
  sample.append(sum_diag[i])
  i += 1
print(matrix)
print('Сумма значений на диагонали', sum(sample))

[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
Сумма значений на диагонали 55


## Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3


In [14]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

In [15]:
from numpy import linalg

In [16]:
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [18]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

## Задача 4 домашнего задания

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [21]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:



In [23]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [30]:
def cosine( a, b ):
    """Подсчет косинуса угла между векторами a, b по их координатам"""
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [35]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
k = 1
p = 0
for i in users_stats:
    if cosine(next_user_stats, i) > p:
        p = cosine(next_user_stats, i)
        user = k
    k+=1
print('Самый похожий пользователь: ', user)

Самый похожий пользователь:  8
